console.log(!true);
var x=2,y=3;
console.log("logical operators");
console.log("x=2,y=3");
console.log("x>y && y<x",x>y && y<x);
console.log("x=2 || y=5", x==2 || y == 5);
console.log("!(x>y)", !(x>y));
console.log("");
console.log("comparision operators");
var a=8,b=10,c="a";
console.log("a=8,b=10");
console.log("a==5", a==5);
console.log("a===8", a===8);
console.log("a===8: 8value as string" , a==="8");
console.log("a!=5", a!=5);
console.log("a!==8", a!==8);
console.log("a!==8 here i gave 8 as string", a!=="8");//here i gave b as string
console.log("a>=b", a>=b);
console.log("b<=b", b<=b);
var p=10;
console.log("Assignment operators");
console.log("p=10");
console.log("p+=20", p+=20);
console.log("p-=20", p-=20);
console.log("p/=2", p/=2);
console.log("p%=5", p%=5);
console.log("p%=2", p%=2);
console.log("6**3", 6**3);
console.log("Arithmetic operators");
console.log("p*3 now p value is 5" , p*3);
